// ISO-3166 country list and IANA timezone list used by the
// Profile -> Settings -> Regional Settings UI.

export const LANGUAGES = [
    { code: 'en-US', label: 'English (United States) — en-US' },
];

// ISO-3166-1 alpha-2 country codes + names.
export const COUNTRIES = [
    { code: 'AF', name: 'Afghanistan' }, { code: 'AL', name: 'Albania' },
    { code: 'DZ', name: 'Algeria' }, { code: 'AS', name: 'American Samoa' },
    { code: 'AD', name: 'Andorra' }, { code: 'AO', name: 'Angola' },
    { code: 'AI', name: 'Anguilla' }, { code: 'AQ', name: 'Antarctica' },
    { code: 'AG', name: 'Antigua and Barbuda' }, { code: 'AR', name: 'Argentina' },
    { code: 'AM', name: 'Armenia' }, { code: 'AW', name: 'Aruba' },
    { code: 'AU', name: 'Australia' }, { code: 'AT', name: 'Austria' },
    { code: 'AZ', name: 'Azerbaijan' }, { code: 'BS', name: 'Bahamas' },
    { code: 'BH', name: 'Bahrain' }, { code: 'BD', name: 'Bangladesh' },
    { code: 'BB', name: 'Barbados' }, { code: 'BY', name: 'Belarus' },
    { code: 'BE', name: 'Belgium' }, { code: 'BZ', name: 'Belize' },
    { code: 'BJ', name: 'Benin' }, { code: 'BM', name: 'Bermuda' },
    { code: 'BT', name: 'Bhutan' }, { code: 'BO', name: 'Bolivia' },
    { code: 'BA', name: 'Bosnia and Herzegovina' }, { code: 'BW', name: 'Botswana' },
    { code: 'BR', name: 'Brazil' }, { code: 'IO', name: 'British Indian Ocean Territory' },
    { code: 'BN', name: 'Brunei Darussalam' }, { code: 'BG', name: 'Bulgaria' },
    { code: 'BF', name: 'Burkina Faso' }, { code: 'BI', name: 'Burundi' },
    { code: 'CV', name: 'Cabo Verde' }, { code: 'KH', name: 'Cambodia' },
    { code: 'CM', name: 'Cameroon' }, { code: 'CA', name: 'Canada' },
    { code: 'KY', name: 'Cayman Islands' }, { code: 'CF', name: 'Central African Republic' },
    { code: 'TD', name: 'Chad' }, { code: 'CL', name: 'Chile' },
    { code: 'CN', name: 'China' }, { code: 'CO', name: 'Colombia' },
    { code: 'KM', name: 'Comoros' }, { code: 'CG', name: 'Congo' },
    { code: 'CD', name: 'Congo (DRC)' }, { code: 'CK', name: 'Cook Islands' },
    { code: 'CR', name: 'Costa Rica' }, { code: 'CI', name: "Côte d'Ivoire" },
    { code: 'HR', name: 'Croatia' }, { code: 'CU', name: 'Cuba' },
    { code: 'CY', name: 'Cyprus' }, { code: 'CZ', name: 'Czechia' },
    { code: 'DK', name: 'Denmark' }, { code: 'DJ', name: 'Djibouti' },
    { code: 'DM', name: 'Dominica' }, { code: 'DO', name: 'Dominican Republic' },
    { code: 'EC', name: 'Ecuador' }, { code: 'EG', name: 'Egypt' },
    { code: 'SV', name: 'El Salvador' }, { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'ER', name: 'Eritrea' }, { code: 'EE', name: 'Estonia' },
    { code: 'SZ', name: 'Eswatini' }, { code: 'ET', name: 'Ethiopia' },
    { code: 'FJ', name: 'Fiji' }, { code: 'FI', name: 'Finland' },
    { code: 'FR', name: 'France' }, { code: 'GF', name: 'French Guiana' },
    { code: 'PF', name: 'French Polynesia' }, { code: 'GA', name: 'Gabon' },
    { code: 'GM', name: 'Gambia' }, { code: 'GE', name: 'Georgia' },
    { code: 'DE', name: 'Germany' }, { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' }, { code: 'GR', name: 'Greece' },
    { code: 'GL', name: 'Greenland' }, { code: 'GD', name: 'Grenada' },
    { code: 'GP', name: 'Guadeloupe' }, { code: 'GU', name: 'Guam' },
    { code: 'GT', name: 'Guatemala' }, { code: 'GG', name: 'Guernsey' },
    { code: 'GN', name: 'Guinea' }, { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana' }, { code: 'HT', name: 'Haiti' },
    { code: 'HN', name: 'Honduras' }, { code: 'HK', name: 'Hong Kong' },
    { code: 'HU', name: 'Hungary' }, { code: 'IS', name: 'Iceland' },
    { code: 'IN', name: 'India' }, { code: 'ID', name: 'Indonesia' },
    { code: 'IR', name: 'Iran' }, { code: 'IQ', name: 'Iraq' },
    { code: 'IE', name: 'Ireland' }, { code: 'IM', name: 'Isle of Man' },
    { code: 'IL', name: 'Israel' }, { code: 'IT', name: 'Italy' },
    { code: 'JM', name: 'Jamaica' }, { code: 'JP', name: 'Japan' },
    { code: 'JE', name: 'Jersey' }, { code: 'JO', name: 'Jordan' },
    { code: 'KZ', name: 'Kazakhstan' }, { code: 'KE', name: 'Kenya' },
    { code: 'KI', name: 'Kiribati' }, { code: 'KP', name: 'Korea (North)' },
    { code: 'KR', name: 'Korea (South)' }, { code: 'KW', name: 'Kuwait' },
    { code: 'KG', name: 'Kyrgyzstan' }, { code: 'LA', name: 'Laos' },
    { code: 'LV', name: 'Latvia' }, { code: 'LB', name: 'Lebanon' },
    { code: 'LS', name: 'Lesotho' }, { code: 'LR', name: 'Liberia' },
    { code: 'LY', name: 'Libya' }, { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuania' }, { code: 'LU', name: 'Luxembourg' },
    { code: 'MO', name: 'Macao' }, { code: 'MG', name: 'Madagascar' },
    { code: 'MW', name: 'Malawi' }, { code: 'MY', name: 'Malaysia' },
    { code: 'MV', name: 'Maldives' }, { code: 'ML', name: 'Mali' },
    { code: 'MT', name: 'Malta' }, { code: 'MH', name: 'Marshall Islands' },
    { code: 'MQ', name: 'Martinique' }, { code: 'MR', name: 'Mauritania' },
    { code: 'MU', name: 'Mauritius' }, { code: 'YT', name: 'Mayotte' },
    { code: 'MX', name: 'Mexico' }, { code: 'FM', name: 'Micronesia' },
    { code: 'MD', name: 'Moldova' }, { code: 'MC', name: 'Monaco' },
    { code: 'MN', name: 'Mongolia' }, { code: 'ME', name: 'Montenegro' },
    { code: 'MS', name: 'Montserrat' }, { code: 'MA', name: 'Morocco' },
    { code: 'MZ', name: 'Mozambique' }, { code: 'MM', name: 'Myanmar' },
    { code: 'NA', name: 'Namibia' }, { code: 'NR', name: 'Nauru' },
    { code: 'NP', name: 'Nepal' }, { code: 'NL', name: 'Netherlands' },
    { code: 'NC', name: 'New Caledonia' }, { code: 'NZ', name: 'New Zealand' },
    { code: 'NI', name: 'Nicaragua' }, { code: 'NE', name: 'Niger' },
    { code: 'NG', name: 'Nigeria' }, { code: 'NU', name: 'Niue' },
    { code: 'NF', name: 'Norfolk Island' }, { code: 'MK', name: 'North Macedonia' },
    { code: 'MP', name: 'Northern Mariana Islands' }, { code: 'NO', name: 'Norway' },
    { code: 'OM', name: 'Oman' }, { code: 'PK', name: 'Pakistan' },
    { code: 'PW', name: 'Palau' }, { code: 'PS', name: 'Palestine' },
    { code: 'PA', name: 'Panama' }, { code: 'PG', name: 'Papua New Guinea' },
    { code: 'PY', name: 'Paraguay' }, { code: 'PE', name: 'Peru' },
    { code: 'PH', name: 'Philippines' }, { code: 'PN', name: 'Pitcairn' },
    { code: 'PL', name: 'Poland' }, { code: 'PT', name: 'Portugal' },
    { code: 'PR', name: 'Puerto Rico' }, { code: 'QA', name: 'Qatar' },
    { code: 'RE', name: 'Réunion' }, { code: 'RO', name: 'Romania' },
    { code: 'RU', name: 'Russia' }, { code: 'RW', name: 'Rwanda' },
    { code: 'BL', name: 'Saint Barthélemy' }, { code: 'SH', name: 'Saint Helena' },
    { code: 'KN', name: 'Saint Kitts and Nevis' }, { code: 'LC', name: 'Saint Lucia' },
    { code: 'MF', name: 'Saint Martin (French)' }, { code: 'PM', name: 'Saint Pierre and Miquelon' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines' }, { code: 'WS', name: 'Samoa' },
    { code: 'SM', name: 'San Marino' }, { code: 'ST', name: 'Sao Tome and Principe' },
    { code: 'SA', name: 'Saudi Arabia' }, { code: 'SN', name: 'Senegal' },
    { code: 'RS', name: 'Serbia' }, { code: 'SC', name: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone' }, { code: 'SG', name: 'Singapore' },
    { code: 'SX', name: 'Sint Maarten (Dutch)' }, { code: 'SK', name: 'Slovakia' },
    { code: 'SI', name: 'Slovenia' }, { code: 'SB', name: 'Solomon Islands' },
    { code: 'SO', name: 'Somalia' }, { code: 'ZA', name: 'South Africa' },
    { code: 'SS', name: 'South Sudan' }, { code: 'ES', name: 'Spain' },
    { code: 'LK', name: 'Sri Lanka' }, { code: 'SD', name: 'Sudan' },
    { code: 'SR', name: 'Suriname' }, { code: 'SE', name: 'Sweden' },
    { code: 'CH', name: 'Switzerland' }, { code: 'SY', name: 'Syria' },
    { code: 'TW', name: 'Taiwan' }, { code: 'TJ', name: 'Tajikistan' },
    { code: 'TZ', name: 'Tanzania' }, { code: 'TH', name: 'Thailand' },
    { code: 'TL', name: 'Timor-Leste' }, { code: 'TG', name: 'Togo' },
    { code: 'TK', name: 'Tokelau' }, { code: 'TO', name: 'Tonga' },
    { code: 'TT', name: 'Trinidad and Tobago' }, { code: 'TN', name: 'Tunisia' },
    { code: 'TR', name: 'Türkiye' }, { code: 'TM', name: 'Turkmenistan' },
    { code: 'TC', name: 'Turks and Caicos Islands' }, { code: 'TV', name: 'Tuvalu' },
    { code: 'UG', name: 'Uganda' }, { code: 'UA', name: 'Ukraine' },
    { code: 'AE', name: 'United Arab Emirates' }, { code: 'GB', name: 'United Kingdom' },
    { code: 'US', name: 'United States' }, { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan' }, { code: 'VU', name: 'Vanuatu' },
    { code: 'VA', name: 'Vatican City' }, { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Vietnam' }, { code: 'VG', name: 'Virgin Islands (British)' },
    { code: 'VI', name: 'Virgin Islands (US)' }, { code: 'WF', name: 'Wallis and Futuna' },
    { code: 'EH', name: 'Western Sahara' }, { code: 'YE', name: 'Yemen' },
    { code: 'ZM', name: 'Zambia' }, { code: 'ZW', name: 'Zimbabwe' },
];

// Common IANA timezones (~50). Format: { value: IANA, label: UI label }.
export const TIMEZONES = [
    { value: 'UTC', label: 'UTC — Coordinated Universal Time' },
    { value: 'America/New_York', label: 'Eastern Time (EST/EDT) — America/New_York' },
    { value: 'America/Chicago', label: 'Central Time (CST/CDT) — America/Chicago' },
    { value: 'America/Denver', label: 'Mountain Time (MST/MDT) — America/Denver' },
    { value: 'America/Phoenix', label: 'Mountain Time (no DST) — America/Phoenix' },
    { value: 'America/Los_Angeles', label: 'Pacific Time (PST/PDT) — America/Los_Angeles' },
    { value: 'America/Anchorage', label: 'Alaska Time — America/Anchorage' },
    { value: 'Pacific/Honolulu', label: 'Hawaii Time — Pacific/Honolulu' },
    { value: 'America/Toronto', label: 'Eastern (Canada) — America/Toronto' },
    { value: 'America/Vancouver', label: 'Pacific (Canada) — America/Vancouver' },
    { value: 'America/Mexico_City', label: 'Central Mexico — America/Mexico_City' },
    { value: 'America/Sao_Paulo', label: 'Brasília — America/Sao_Paulo' },
    { value: 'America/Argentina/Buenos_Aires', label: 'Argentina — Buenos Aires' },
    { value: 'Europe/London', label: 'London (GMT/BST) — Europe/London' },
    { value: 'Europe/Dublin', label: 'Dublin — Europe/Dublin' },
    { value: 'Europe/Paris', label: 'Paris (CET/CEST) — Europe/Paris' },
    { value: 'Europe/Berlin', label: 'Berlin (CET/CEST) — Europe/Berlin' },
    { value: 'Europe/Madrid', label: 'Madrid — Europe/Madrid' },
    { value: 'Europe/Rome', label: 'Rome — Europe/Rome' },
    { value: 'Europe/Amsterdam', label: 'Amsterdam — Europe/Amsterdam' },
    { value: 'Europe/Stockholm', label: 'Stockholm — Europe/Stockholm' },
    { value: 'Europe/Warsaw', label: 'Warsaw — Europe/Warsaw' },
    { value: 'Europe/Athens', label: 'Athens (EET/EEST) — Europe/Athens' },
    { value: 'Europe/Istanbul', label: 'Istanbul — Europe/Istanbul' },
    { value: 'Europe/Moscow', label: 'Moscow — Europe/Moscow' },
    { value: 'Africa/Cairo', label: 'Cairo — Africa/Cairo' },
    { value: 'Africa/Lagos', label: 'Lagos — Africa/Lagos' },
    { value: 'Africa/Johannesburg', label: 'Johannesburg — Africa/Johannesburg' },
    { value: 'Africa/Nairobi', label: 'Nairobi — Africa/Nairobi' },
    { value: 'Asia/Dubai', label: 'Dubai — Asia/Dubai' },
    { value: 'Asia/Tehran', label: 'Tehran — Asia/Tehran' },
    { value: 'Asia/Karachi', label: 'Karachi — Asia/Karachi' },
    { value: 'Asia/Kolkata', label: 'India (IST) — Asia/Kolkata' },
    { value: 'Asia/Kathmandu', label: 'Kathmandu — Asia/Kathmandu' },
    { value: 'Asia/Dhaka', label: 'Dhaka — Asia/Dhaka' },
    { value: 'Asia/Bangkok', label: 'Bangkok — Asia/Bangkok' },
    { value: 'Asia/Jakarta', label: 'Jakarta — Asia/Jakarta' },
    { value: 'Asia/Singapore', label: 'Singapore — Asia/Singapore' },
    { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur — Asia/Kuala_Lumpur' },
    { value: 'Asia/Manila', label: 'Manila — Asia/Manila' },
    { value: 'Asia/Hong_Kong', label: 'Hong Kong — Asia/Hong_Kong' },
    { value: 'Asia/Shanghai', label: 'Shanghai (CST) — Asia/Shanghai' },
    { value: 'Asia/Taipei', label: 'Taipei — Asia/Taipei' },
    { value: 'Asia/Seoul', label: 'Seoul — Asia/Seoul' },
    { value: 'Asia/Tokyo', label: 'Tokyo (JST) — Asia/Tokyo' },
    { value: 'Australia/Perth', label: 'Perth — Australia/Perth' },
    { value: 'Australia/Adelaide', label: 'Adelaide — Australia/Adelaide' },
    { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT) — Australia/Sydney' },
    { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT) — Pacific/Auckland' },
];
